FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive

# Actualiza ubuntu, instala todas las dependencias para apache2

RUN apt-get update && apt-get install -y \
    curl \
    git \
    build-essential \
    apache2 \ 
    mysql-server \
    phpmyadmin

EXPOSE 80










