version: '3.9'
services:
  webserver:
    container_name: PHP_webService
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./www/:/var/www/
    depends_on:
      - database

  database:
    container_name: MySQL
    image: mysql:8.2
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: 1234
    ports:
      - 3306:3306
    


  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8001:80
    environment:
      PMA_HOST: mysql
      PMA_PASSWORD: 1234
    restart: unless-stopped
