version: '1'
services:
  database:
    container_name: MySQL
    image: mysql:8.2
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: 1234
    ports:
      - 3306:3306